[package]
name = "adventofcode"
version = "0.1.0"
authors = ["Peter Tseng <pht24@cornell.edu>"]
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "my_benchmark"
harness = false
